services:
  - type: web
    name: quality-bi
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node --loader tsx server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
